title: CTI Hub
theme: minima
markdown: kramdown

# Enable navigation links
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Optional: Navigation order
collections:
  pages:
    output: true
